### ISSUE TITLE
Can't seem to connect o Office365 mail.

### ISSUE THREAD

**Issue by ConorIA** [owncloudarchive/mail#1653]
### Steps to reproduce
1. Add new account firstname.lastname@mail.utoronto.ca
2. Set up incoming to: outlook.office365.com:993; outgoing to: smtp.office365.com:587

### Expected behaviour
School account should be added

### Actual behaviour
Adding account fails with a `Creating account failed: Server denied authentication.`	

### Mail app

**Mail app version:** 0.6.0

**Mailserver or service:** Office365 with school domain

**Transport security - IMAP:** SSL

**Transport security - SMTP:** STARTTLS

**Number of accounts:** 1

### Server configuration
**Operating system**: Linux/Docker

**Web server:** Nginx

**Database:** Mysql 7.0.11

**PHP version:** 7.0.11

**Version:** 10.0.1

**Updated from an older version or fresh install:** Upgrade, but didn't work on a fresh install either.

**List of activated apps:** 
- bookmarks
- calendar
- tasks
- mail
- contacts
- documents
- files
- gallery 
- notes

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/data',
...
  'trusted_domains' => 
  array (
...
  ),
  'overwrite.cli.url' => 'https://172.17.0.7:8888',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'db_nextcloud',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
...
  'logtimezone' => 'UTC',
  'installed' => true,
  'overwriteprotocol' => 'https',
  'appstore.experimental.enabled' => true,
  'loglevel' => 3,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'theme' => '',
  'maintenance' => false,
...
  'updater.release.channel' => 'stable',
);
```

#### Client configuration
**Browser:** Brave 0.12.4

**Operating system:** Manjaro Linux x64

##### Web server error log
_nothing relevant_

##### Server log (data/owncloud.log or data/nextcloud.log)
[nextcloud.txt](https://github.com/owncloudarchive/mail/files/531496/nextcloud.txt)

##### Horde IMAP log (data/horde_imap.log)
_does not exist_

##### Horde SMTP log (data/horde_smtp.log)
_does not exist_

**Comment by MariusBluem** [comment]
> Version: 10.0.1

Seems that you are using Nextcloud 😉 We have moved the development of the Mail app into another repository. Please open this issue here: https://github.com/nextcloud/mail. Thank you 😅

**Comment by ConorIA** [comment]
@MariusBluem I'm on it! Thanks.
