### ISSUE TITLE
Ability to add attachments from the computer

### ISSUE THREAD

**Issue by jancborchardt** [owncloudarchive/mail#462]
Currently it’s only possible to add attachments from ownCloud Files. We should also enable people to upload attachments from their computer. While it’s a cool integration, we don’t want to force people to need to upload their stuff to ownCloud before they can attach it to their Mails.

(This should of course also work for replying: https://github.com/owncloud/mail/issues/460)

**Comment by Xenopathic** [comment]
This seems like it'll be a big feature - deferring to 0.2

**Comment by jancborchardt** [comment]
Not sure, we have adding attachments from files already. Maybe this is the next thing @DeepDiver1975 wants to work on? ;)

**Comment by jancborchardt** [comment]
Keeping this one in 0.1 after talking to @DeepDiver1975. Thanks for cleaning up the other issues though @Xenopathic! :)

**Comment by jancborchardt** [comment]
@DeepDiver1975 I’m deferring again to 0.2 since it doesn’t look like we’ll be able to get this for 0.1

**Comment by DeepDiver1975** [comment]
WAIT ... I'm HACKING ON THIS AT THE MOMENT!

**Comment by jancborchardt** [comment]
Ohh good news! :) (Also remember it for replying then https://github.com/owncloud/mail/issues/460)

**Comment by DeepDiver1975** [comment]
I'm too stupid for jquery -> 0.2

**Comment by aidanamavi** [comment]
I took a look at this issue, and came to the conclusion that we need to access Files app classes or apis to manage/upload a file.

I'm either not aware of how to do this and need some direction, or the current classes for file upload and management in the File app need to be extended. As @DeepDiver1975 noticed, we could spend a lot of hours hacking this only to revert our commits for entirely new ones later, or do this properly the first time with global file management classes/functions.

In the upload.php file for the Files app, there is this TODO comment.
```
	// TODO: ideally this code should be in files_sharing/ajax/upload.php
	// and the upload/file transfer code needs to be refactored into a utility method
	// that could be used there
```

**Comment by DeepDiver1975** [comment]
There us no need to integrate the files app.

The mail composer form has to be converted to properly use jquery upload (this is the part I had my head aches with).

The php side is rather easy to be implemented in the account controller.

**Comment by aidanamavi** [comment]
Okay. I'll give it another shot tomorrow. I'll adjust the controller, and create the jQuery for it. Thanks for the quick feedback. :)

**Comment by DeepDiver1975** [comment]
Regarding the php side:  the request object has a method like getFiles () or something.  This is rather trivial to implement. 

Fun part is the js side .... have fun!

**Comment by jancborchardt** [comment]
@aidanamavi are you still working on this? Probably @LukasReschke (AnybodyElse on IRC) can help you here.

**Comment by aidanamavi** [comment]
@jancborchardt I gave it two or three days of study, but I couldn't wrap my head around the back end. I referenced other apps, including core, and the same process was done differently for each one, so all I accomplished was the front end. It would be best to have someone else assigned to this issue.

**Comment by DeepDiver1975** [comment]
I finally got a very basic version up and running - see #811

**Comment by jancborchardt** [comment]
Not gonna happen in a week until 0.2 -> 0.3

**Comment by stefanhuber** [comment]
Hi, is there any progress on this issue? Is there anything one could do to help?

**Comment by jancborchardt** [comment]
@stefanhuber I'm not aware if any work in progress on this, so you are welcome to go for it! :)

Let us know if you have any questions. Maybe @christophwurst @Henni @Gomez can give some pointers.

**Comment by jancborchardt** [comment]
If you use IRC, you are also very welcome in our channel #owncloud-mail on freenode.

**Comment by scheppi2610** [comment]
Is there any progress?
Why dont you just reference to file-upload-function from files-app ? Better than nothing.

**Comment by jancborchardt** [comment]
@scheppi2610 please note that this app is in the »archive« and is not maintained here anymore. For active development please see https://github.com/nextcloud/mail

There is also an open pull request for this issue: https://github.com/nextcloud/mail/pull/4 – contributions very appreciated. :)
